[build]
  # BỎ TRỐNG LỆNH BUILD
  command = ""
  # BỎ TRỐNG THƯ MỤC PUBLIC
  publish = ""

[functions]
  # ĐƯỜNG DẪN ĐẾN FUNCTIONS
  directory = "netlify/functions"
  # Thời gian timeout cho Function
  timeout = 10
