# File: netlify.toml - Cấu hình Build cho các Function (Serverless)

[build]
# Thư mục nơi Netlify sẽ tìm kiếm các Functions
functions = "netlify/functions" 
# Thư mục nơi chứa các file tĩnh (files from index.html)
publish = "." 
# Lệnh Build (Cài đặt dependencies cho Function)
command = "npm install" 
